import { createClient } from '@supabase/supabase-js'

const supabase = createClient(
  'https://gmnigwwhaoylcsueqmic.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdtbmlnd3doYW95bGNzdWVxbWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA4NDI3OTQsImV4cCI6MjA4NjQxODc5NH0.mtUlezYG-JMX_VMu5Nd7iAzF8WPUAo3f4DiPlCW6zMM'
)

function g(name, side, subgroup, likelihood = 'green', has_plus_one = false, plus_one_name = null, notes = null) {
  return { name, side, subgroup, likelihood, has_plus_one, plus_one_name, phone: null, notes }
}

const guests = [
  // ===== סוסון - חברים =====
  g('בית', 'suson', 'friends'),
  g('איתי', 'suson', 'friends'),
  g('אנה', 'suson', 'friends'),
  g('תומר', 'suson', 'friends'),
  g('רוני', 'suson', 'friends'),
  g('טורצ׳יק', 'suson', 'friends'),
  g('ליאור', 'suson', 'friends'),
  g('מיה', 'suson', 'friends'),
  g('עוז', 'suson', 'friends'),
  g('נטע', 'suson', 'friends'),
  g('ניר', 'suson', 'friends'),
  g('ניז׳ני', 'suson', 'friends'),
  g('זוהר', 'suson', 'friends'),
  g('יותם', 'suson', 'friends'),
  g('קרן', 'suson', 'friends'),
  g('נועה', 'suson', 'friends'),
  g('יוקל', 'suson', 'friends'),
  g('יהודה', 'suson', 'friends'),
  g('תומר', 'suson', 'friends'),
  g('גלעד', 'suson', 'friends'),
  g('אלינור', 'suson', 'friends'),

  // ===== סוסון - שונות =====
  g('ניב', 'suson', 'other'),
  g('ברגיל', 'suson', 'other'),
  g('יהלי', 'suson', 'other'),
  g('גיא', 'suson', 'other'),
  g('סתיו', 'suson', 'other'),
  g('עומר לוי', 'suson', 'other'),
  g('עמית', 'suson', 'other'),
  g('רועי', 'suson', 'other'),
  g('סיוון', 'suson', 'other'),
  g('אילת', 'suson', 'other'),
  g('ג\'ייקוב', 'suson', 'other'),
  g('בן', 'suson', 'other'),

  // ===== סוסון - צבא =====
  g('תומר', 'suson', 'army'),
  g('ליבשטיין', 'suson', 'army'),
  g('לידור', 'suson', 'army'),
  g('יעקב', 'suson', 'army'),
  g('דיויד', 'suson', 'army'),
  g('הנדלסמן', 'suson', 'army'),
  g('חוגי', 'suson', 'army'),
  g('שוסף', 'suson', 'army'),
  g('שחורי', 'suson', 'army'),
  g('גיא', 'suson', 'army'),
  g('ליעד', 'suson', 'army'),
  g('אסף', 'suson', 'army'),
  g('מושון', 'suson', 'army'),
  g('יפתח', 'suson', 'army'),
  g('גורביץ׳', 'suson', 'army'),
  g('שוקי', 'suson', 'army'),
  g('זיגי', 'suson', 'army'),
  g('אמתי', 'suson', 'army'),
  g('סיילס', 'suson', 'army'),
  g('איתמר', 'suson', 'army'),
  g('יובל', 'suson', 'army'),
  g('אמרו', 'suson', 'army'),
  g('שפיצן', 'suson', 'army'),
  g('כבירי', 'suson', 'army'),

  // ===== סוסון - משפחה =====
  g('אמא', 'suson', 'family'),
  g('אבא', 'suson', 'family'),
  g('שירה', 'suson', 'family'),
  g('סבא', 'suson', 'family'),
  g('סבתא', 'suson', 'family'),
  g('סבא', 'suson', 'family', 'green', false, null, 'סבא 2'),
  g('סבתא', 'suson', 'family', 'green', false, null, 'סבתא 2'),
  g('תותי', 'suson', 'family'),
  g('יעקב', 'suson', 'family'),
  g('שלי', 'suson', 'family'),
  g('אילן', 'suson', 'family'),
  g('שלומית', 'suson', 'family'),
  g('מיכאל', 'suson', 'family'),
  g('אנה', 'suson', 'family'),
  g('ג׳ון ג׳ון', 'suson', 'family', 'yellow'),
  g('אבי', 'suson', 'family', 'yellow'),
  g('סולמון', 'suson', 'family', 'yellow'),
  g('אלי', 'suson', 'family', 'yellow'),
  g('שפרה', 'suson', 'family'),
  g('ריימונד', 'suson', 'family'),
  // בני דודים אמא
  g('דויד', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('עמליה', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('עמית', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('הילה', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('נדב', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('איתי', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('הדר', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('עידו', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('אגם', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('אודי', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('ביאטה', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('מיכל', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('יעל', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('נועה', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('אסף', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('שני', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('ליהיא', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('ירדן', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('תומר', 'suson', 'family', 'green', false, null, 'בני דודים אמא'),
  g('שירה מיירו', 'suson', 'family', 'yellow'),
  g('מארק מיירו', 'suson', 'family', 'yellow'),
  g('נוח', 'suson', 'family', 'yellow'),
  g('עילאי', 'suson', 'family', 'yellow'),
  g('רייצ׳ל', 'suson', 'family', 'yellow', true),
  g('נאורה', 'suson', 'family', 'yellow'),
  g('סרג׳יו', 'suson', 'family', 'yellow'),
  g('אודי', 'suson', 'family'),
  g('דורי', 'suson', 'family'),
  g('מורלי', 'suson', 'family'),
  g('אבי', 'suson', 'family'),
  g('מעיין', 'suson', 'family', 'yellow', true),
  g('רעות', 'suson', 'family', 'yellow', true),
  g('רותם', 'suson', 'family', 'yellow', true),

  // ===== סוסון - חברים של ההורים =====
  g('שרון גנות', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('עידו גנות', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('שירה גנות', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('מאיה', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('דנה', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('תום', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('ויויאן', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('דן אקשטיין', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('אסף א', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('עמית', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('אורית האוזמן', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('אודי', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('נועה האוזמן', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('בן האוזמן', 'suson', 'other', 'yellow', false, null, 'חברים של ההורים'),
  g('מיכל האוזמן', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('שירה האוזמן', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('דורית רצבי', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('יואל רצבי', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('שיר', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('טל', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('דורית להב', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('צורי', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('ארז', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('שרית', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('זאבי', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('תמרי', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('דליה סודרי', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('ברק סודרי', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('יעל פינקלשטיין', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('בועז פינקלשטיין', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('נדב פ', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('רומי פ', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  g('אדווה', 'suson', 'other', 'green', false, null, 'חברים של ההורים'),
  // חברים אבא
  g('גדי', 'suson', 'other', 'green', false, null, 'חברים אבא'),
  g('מושיקו', 'suson', 'other', 'green', true, null, 'חברים אבא'),
  g('דרור', 'suson', 'other', 'green', false, null, 'חברים אבא'),

  // ===== סוסון - עבודה =====
  g('אלי', 'suson', 'work'),
  g('עדי', 'suson', 'work'),
  g('עודד', 'suson', 'work'),
  g('דור', 'suson', 'work'),
  g('פוטי', 'suson', 'work'),
  g('יאיר', 'suson', 'work'),
  g('יונתן', 'suson', 'work'),
  g('ניב', 'suson', 'work'),
  g('סבג', 'suson', 'work'),
  g('שייקה', 'suson', 'work'),
  g('תמיר', 'suson', 'work'),
  g('אסף', 'suson', 'work'),
  g('עומרי', 'suson', 'work'),
  g('אורי', 'suson', 'work'),
  g('אמיר', 'suson', 'work'),
  g('שי', 'suson', 'work'),
  g('עדן', 'suson', 'work'),
  g('עומר', 'suson', 'work'),
  g('תומר', 'suson', 'work'),
  g('שחר', 'suson', 'work'),
  g('אדווה', 'suson', 'work'),
  g('קופר', 'suson', 'work'),
  g('יואב', 'suson', 'work'),

  // ===================================================
  // ===== סוסונית - חברות =====
  // ===================================================
  g('תהילה', 'susonit', 'friends'),
  g('אשד', 'susonit', 'friends'),
  g('עדן', 'susonit', 'friends'),
  g('יוסי', 'susonit', 'friends'),
  g('ניב', 'susonit', 'friends'),
  g('גוב', 'susonit', 'friends'),
  g('תומר', 'susonit', 'friends'),
  g('פלג', 'susonit', 'friends'),
  g('עוז', 'susonit', 'friends'),
  g('עד', 'susonit', 'friends'),
  g('ניב', 'susonit', 'friends'),
  g('דף', 'susonit', 'friends'),
  g('יניב', 'susonit', 'friends'),
  g('נטע ניב', 'susonit', 'friends'),
  g('דור', 'susonit', 'friends'),
  g('תמר קיסר', 'susonit', 'friends'),
  g('שני מיכאלי', 'susonit', 'friends'),
  g('שושני', 'susonit', 'friends'),
  g('שני לברן', 'susonit', 'friends'),
  g('עבאדי', 'susonit', 'friends'),
  g('עומר רו', 'susonit', 'friends'),
  g('אוהד כה', 'susonit', 'friends'),
  g('רותם איתן', 'susonit', 'friends'),
  g('עמית לי', 'susonit', 'friends'),
  g('עמית גולן', 'susonit', 'friends'),
  g('רותם ש', 'susonit', 'friends'),
  g('רון', 'susonit', 'friends'),
  g('עדן פריג', 'susonit', 'friends'),
  g('עומרי אודם', 'susonit', 'friends'),
  g('גיא גלנט', 'susonit', 'friends'),
  g('עומר קירש', 'susonit', 'friends'),
  g('מיכ', 'susonit', 'friends'),
  g('שלו', 'susonit', 'friends'),
  g('אלה רוכמן', 'susonit', 'friends'),
  g('יונתן', 'susonit', 'friends'),
  g('הגר', 'susonit', 'friends'),
  g('מייץ', 'susonit', 'friends'),
  g('יפתח', 'susonit', 'friends'),
  g('יסמין', 'susonit', 'friends'),
  g('פלדמן', 'susonit', 'friends'),
  g('יערה', 'susonit', 'friends'),
  g('אורי בר אבן', 'susonit', 'friends', 'yellow'),
  g('טלכו', 'susonit', 'friends', 'yellow'),

  // ===== סוסונית - עבודה =====
  g('הדר', 'susonit', 'work'),
  g('עמית', 'susonit', 'work'),
  g('שלי', 'susonit', 'work'),
  g('אירית', 'susonit', 'work'),
  g('אלון ק', 'susonit', 'work', 'yellow'),
  g('עגור', 'susonit', 'work', 'yellow'),
  g('יעל', 'susonit', 'work'),
  g('תמר', 'susonit', 'work'),
  g('בר', 'susonit', 'work'),
  g('רועי', 'susonit', 'work'),
  g('עומר', 'susonit', 'work'),
  g('אור גאני', 'susonit', 'work'),
  g('פרניק', 'susonit', 'work'),
  g('שלו', 'susonit', 'work'),
  g('מקסים', 'susonit', 'work'),
  g('תגר', 'susonit', 'work'),
  g('רן', 'susonit', 'work', 'yellow'),
  g('יונתן', 'susonit', 'work', 'yellow'),
  g('יואב', 'susonit', 'work'),
  g('דור', 'susonit', 'work'),
  g('תמר', 'susonit', 'work'),
  g('איתי', 'susonit', 'work'),
  g('נעם ורון', 'susonit', 'work'),
  g('נדב', 'susonit', 'work'),
  g('עומר גנץ', 'susonit', 'work'),
  g('ברוקר', 'susonit', 'work'),
  g('רועי זיו', 'susonit', 'work'),
  g('עדי', 'susonit', 'work'),
  g('אלונה', 'susonit', 'work'),
  g('מיקה', 'susonit', 'work', 'yellow'),
  g('שטרן', 'susonit', 'work'),
  g('שירה צמחי', 'susonit', 'work'),
  g('רעות', 'susonit', 'work'),
  g('לי', 'susonit', 'work'),
  g('ספיר', 'susonit', 'work'),
  g('זהר', 'susonit', 'work'),
  g('פוביצר', 'susonit', 'work'),
  g('יונתן אריאל', 'susonit', 'work'),
  g('שחורי', 'susonit', 'work'),
  g('טל ליברטי', 'susonit', 'work'),
  g('הגר שמואלי', 'susonit', 'work'),
  g('גיל', 'susonit', 'work'),
  g('בנדה', 'susonit', 'work'),

  // ===== סוסונית - משפחה =====
  g('אבא', 'susonit', 'family'),
  g('אמא', 'susonit', 'family'),
  g('נטע', 'susonit', 'family'),
  g('מור', 'susonit', 'family'),
  g('אמיתי', 'susonit', 'family'),
  g('גל', 'susonit', 'family'),
  g('מיכאל', 'susonit', 'family'),
  g('יואב', 'susonit', 'family'),
  g('ניצה', 'susonit', 'family'),
  g('אלי', 'susonit', 'family'),
  g('טל', 'susonit', 'family'),
  g('עומר', 'susonit', 'family'),
  g('רני', 'susonit', 'family'),
  g('ענבר', 'susonit', 'family'),
  g('יואל', 'susonit', 'family'),
  g('גיא', 'susonit', 'family'),
  g('אורי', 'susonit', 'family'),
  g('יובל', 'susonit', 'family'),
  g('גלי', 'susonit', 'family'),
  g('מאיה', 'susonit', 'family'),
  g('ליאור', 'susonit', 'family'),
  g('עילאי', 'susonit', 'family'),
  g('ינאי', 'susonit', 'family'),
  g('יהודית', 'susonit', 'family'),
  g('מירה', 'susonit', 'family'),
  // בת דודה אמא
  g('עמית', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('יעל', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('תומי', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('הבת של עמית', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('יוחאי', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('יעל', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('נועה', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('אלון', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('מיכל', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('קרן', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('חגי', 'susonit', 'family', 'green', false, null, 'בת דודה אמא'),
  g('רוחלה', 'susonit', 'family'),
  g('טל', 'susonit', 'family'),
  g('עופרי', 'susonit', 'family'),
  g('אלי', 'susonit', 'family'),
  g('ילדה של טל', 'susonit', 'family'),
  g('אור', 'susonit', 'family'),
  g('גל', 'susonit', 'family'),
  g('נורית', 'susonit', 'family'),
  g('פרנק', 'susonit', 'family'),
  g('הדס', 'susonit', 'family'),
  g('מריים ואיתי', 'susonit', 'family', 'green', true, null, 'מגיעים +4 (6 סה״כ)'),
  g('עדה', 'susonit', 'family', 'green', true, null, 'מגיעה +3 (4 סה״כ)'),
  g('דוד ונוי', 'susonit', 'family', 'green', true, null, 'מגיעים +3 (5 סה״כ)'),
  g('איילת ועינן', 'susonit', 'family', 'green', true, null, 'מגיעים +4 (6 סה״כ)'),

  // ===== סוסונית - חברים הורים =====
  g('אמנון', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('תמר', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('עמית', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('גלעד', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('עידו', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('תמי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('טל', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('לימור', 'susonit', 'other', 'green', true, null, 'חברים הורים, מגיעה +3 (4 סה״כ)'),
  g('יעל שוויקי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('מיקי שוויקי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('שירה', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('אמיתי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('גילי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('אורי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('ניצן', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('מירב', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('קרני', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('גאיה', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('אורנית', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('שי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('אבי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('מיכל', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('אורנית רינות', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('יריב', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('שרון כץ', 'susonit', 'other', 'green', true, null, 'חברים הורים'),
  g('דבי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('אסי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('מיכל', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('אבי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('רוחה', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('ראומה', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
  g('אורלי', 'susonit', 'other', 'green', false, null, 'חברים הורים'),
]

async function seed() {
  console.log(`Inserting ${guests.length} guests...`)

  // Insert in batches of 50
  const batchSize = 50
  let inserted = 0

  for (let i = 0; i < guests.length; i += batchSize) {
    const batch = guests.slice(i, i + batchSize)
    const { data, error } = await supabase.from('guests').insert(batch).select('id')

    if (error) {
      console.error(`Error inserting batch starting at index ${i}:`, error.message)
      process.exit(1)
    }

    inserted += data.length
    console.log(`  Inserted ${inserted}/${guests.length}`)
  }

  console.log(`\nDone! ${inserted} guests added.`)

  // Print summary
  const suson = guests.filter(g => g.side === 'suson')
  const susonit = guests.filter(g => g.side === 'susonit')
  console.log(`\nסוסון: ${suson.length}`)
  console.log(`סוסונית: ${susonit.length}`)

  const subgroups = {}
  for (const g of guests) {
    const key = `${g.side} - ${g.subgroup}`
    subgroups[key] = (subgroups[key] || 0) + 1
  }
  console.log('\nBreakdown:')
  for (const [key, count] of Object.entries(subgroups)) {
    console.log(`  ${key}: ${count}`)
  }
}

seed()
